server:
  port: 8077
spring:
  application:
    name: minio-client
  servlet:
    multipart:
      enabled: true
      max-file-size: 500MB
      max-request-size: 500MB
      file-size-threshold: 500MB
  thymeleaf: #thymeleaf配置
    cache: false
    encoding: utf-8
    mode: HTML5
    prefix: classpath:/templates/
    suffix: .html

minio:
  conf:
    url: http://192.168.117.186:9000
    user: minio
    password: 123456789
    path: images
